export const XP=[30,30,40,50,30,30,30,30,30,30,30,30,50,40,30,30,30,30,30,40];
export const STEPS=[2,3,2,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,1];
export function randomStep(value){let n=(Math.imul(value,1664525)+1013904223)>>>0;return {state:n,value:n/4294967296};}
export function packetSpecs(seed){let state=seed>>>0;const next=()=>{let r=randomStep(state);state=r.state;return r.value};return Array.from({length:46},(_,id)=>{const lane=Math.floor(next()*4),bad=next()<.65,label=bad?(next()<.5?'DDoS':'PORT'):(next()<.5?'HTTP':'HTTPS'),speed=48+next()*16;return {id,lane,bad,label,speed,spawn:(id+1)*850,y:45+lane*67};});}
export function packetMetrics(seed,answer,elapsed=Infinity){if(!answer||!Array.isArray(answer.events)||answer.events.length>100||!Number.isInteger(answer.end)||answer.end<1||answer.end>40000||answer.end>elapsed+800)return null;const specs=packetSpecs(seed),blocked=new Set();let count=0,errors=0,last=0;for(const e of answer.events){if(!e||!Number.isInteger(e.id)||!Number.isInteger(e.time)||e.time<last||e.time>answer.end)return null;last=e.time;const p=specs[e.id];if(!p||blocked.has(e.id)||e.time<p.spawn||36+p.speed*(e.time-p.spawn)/1000>586)return null;blocked.add(e.id);if(p.bad)count++;else errors++;}for(const p of specs)if(p.bad&&!blocked.has(p.id)&&p.spawn+(550/p.speed*1000)<=answer.end)errors++;return {count,errors};}
export function validatePacketReplay(seed,answer,elapsed=Infinity){const result=packetMetrics(seed,answer,elapsed);return !!result&&result.count>=8&&result.errors<5;}
export function snakeFood(s){for(let i=0;i<300;i++){let r=randomStep(s.rng);s.rng=r.state;const x=Math.floor(r.value*16);r=randomStep(s.rng);s.rng=r.state;const y=Math.floor(r.value*16);if(!s.body.some(p=>p.x===x&&p.y===y)&&!s.mines.some(p=>p.x===x&&p.y===y))return{x,y};}return{x:0,y:0};}
export function snakeInitial(seed){let s={body:[{x:8,y:8},{x:7,y:8},{x:6,y:8}],direction:1,rng:seed>>>0,mines:[{x:3,y:3},{x:12,y:3},{x:3,y:12}],score:0,ended:false,ticks:0};s.food=snakeFood(s);return s;}
export function snakeStep(s,requested){if(s.ended)return s;const moves=[[0,-1],[1,0],[0,1],[-1,0]];let dir=Number.isInteger(requested)&&requested>=0&&requested<4?requested:s.direction;if((dir+2)%4===s.direction)dir=s.direction;s.direction=dir;let [dx,dy]=moves[dir],head={x:(s.body[0].x+dx+16)%16,y:(s.body[0].y+dy+16)%16};let eats=head.x===s.food.x&&head.y===s.food.y;let body=eats?s.body:s.body.slice(0,-1);s.ticks++;if(body.some(p=>p.x===head.x&&p.y===head.y)||s.mines.some(p=>p.x===head.x&&p.y===head.y)){s.ended=true;return s;}s.body.unshift(head);if(!eats)s.body.pop();else{s.score++;s.food=snakeFood(s);}return s;}
export function validateSnakeReplay(seed,answer,elapsed=Infinity){if(!answer||!Array.isArray(answer.moves)||answer.moves.length>512||answer.moves.length<1||answer.moves.length*180>elapsed+800)return false;let s=snakeInitial(seed);for(const dir of answer.moves){if(!Number.isInteger(dir)||dir<0||dir>3||s.ended||s.score>=4)return false;snakeStep(s,dir);}return !s.ended&&s.score>=4;}
export function validateRobot(answer){if(!Array.isArray(answer)||answer.length>12||answer.length<4)return false;let x=0,y=0;const moves={U:[0,-1],R:[1,0],D:[0,1],L:[-1,0]};for(const m of answer){if(!moves[m])return false;x+=moves[m][0];y+=moves[m][1];if(x<0||x>3||y<0||y>3||x===1&&y===1)return false;}return x===2&&y===2;}
export function validateAnswer(id,step,a,seed,elapsed){if(id===0&&step===0){if(typeof a!=='string'||a.length>200)return false;return a.length>=14&&/[a-zA-Z가-힣]/.test(a)&&/\d/.test(a)&&/[^a-zA-Z0-9가-힣]/.test(a)&&!/(password|qwerty|123456|hacklingo)/i.test(a)&&!(/^(.)\1+$/u.test(a));}
if(id===1)return a===['sender','urgent','link'][step];if(id===2)return a?.line===1&&a?.option===(step===0?0:1);if(id===3)return validatePacketReplay(seed,a,elapsed);if(id===5&&step===0)return a==='scanned';if(id===8&&step===0)return Array.isArray(a)&&a.length===2&&a.includes('address')&&a.includes('school');if(id===10&&step===0)return a?.contacts===false&&a?.mic===false&&a?.location===false;if(id===12)return validateSnakeReplay(seed,a,elapsed);if(id===13&&step===0)return a?.points===5&&a?.blockVirus===true&&a?.tested===true;if(id===14&&step===0)return typeof a==='string'&&a.trim().toUpperCase()==='BYTE';if(id===19)return validateRobot(a);const answers={0:[null,0],4:[1,1],5:[null,1],6:[1,1],7:[1,1],8:[null,1],9:[0,1],10:[null,1],11:[2,0],13:[null,1],14:[null,1],15:[1,1],16:[2,0],17:[1,1],18:[0,1]};return a===answers[id]?.[step]&&a!==undefined;}
