export const XP=[30,30,40,50,30,30,30,30,30,30,30,30,50,40,30,30,30,30,30,40,40,50,50,50,50,50,50];
export const STEPS=[2,3,2,1,2,2,2,2,2,2,2,2,3,2,2,2,2,2,2,1,2,3,3,3,3,3,3];
// These exercises run against disposable virtual records, never real accounts or URLs.
export function scenarioSpec(id,seed){const n=100+(seed>>>0)%800;return {
21:{normal:String(n),exploit:String(n+1),patch:'ownership',context:`로그인: analyst-a · 내 문서 ${n} · analyst-b의 문서 ${n+1}`,code:'return documents[request.id];',fixed:'require(document.owner === session.user);'},
22:{normal:'portal.lab',exploit:'promo.lab',patch:'csrf-token',context:'로그인 쿠키가 있는 가상 송금 서비스 · 출발 사이트만 바꿔보기',code:'if (session) transfer(100);',fixed:'require(validCsrfToken && trustedOrigin);'},
23:{normal:'https://assets.example/banner.png',exploit:'http://intranet.lab/status',patch:'allowlist',context:'가상 이미지 프록시 · assets.example는 외부, intranet.lab은 내부',code:'return fetch(request.url);',fixed:'require(allowedHost && publicAddress);'},
24:{normal:'wrong-password',exploit:`Demo-${n}!`,patch:'mfa',context:`가상 유출 목록: analyst-a / Demo-${n}! · 비밀번호를 재사용한 계정`,code:'return password === storedPassword;',fixed:'require(passwordMatches && secondFactor);'},
25:{normal:'brief.txt',exploit:'../private/incident.txt',patch:'root-boundary',context:'공개 /reports/brief.txt · 비공개 /private/incident.txt',code:'return files[normalize("/reports/" + input)];',fixed:'require(resolvedPath.startsWith("/reports/"));'},
26:{normal:'signal-utils',exploit:'signai-utils',patch:'lockfile',context:'공식 signal-utils · 한 글자가 다른 signai-utils는 가상 변조 패키지',code:'install(registry[input]);',fixed:'require(packageName === approved && hash === lockedHash);'}
}[id]||null;}
export function scenarioLab(id,seed,input,patch='none'){
const spec=scenarioSpec(id,seed);if(!spec||typeof input!=='string'||input.length>120||!['none','cosmetic',spec.patch].includes(patch))return null;
if(![spec.normal,spec.exploit].includes(input))return null;
const attack=input===spec.exploit,protectedMode=patch===spec.patch;let blocked=attack&&protectedMode,status=blocked?403:200,trace=[],data='';
if(id===21){trace=[`GET /documents/${input}`,'session.user = analyst-a',`document.owner = ${attack?'analyst-b':'analyst-a'}`,protectedMode?'소유자 검사 → '+(blocked?'불일치':'일치'):'소유자 검사 없음'];data=blocked?'접근 거부':attack?'가상 문서: 비공개 사고 보고서':'가상 문서: 내 공개 보고서';}
if(id===22){trace=[`Origin = https://${input}`,'Cookie = demo-session (모형)',protectedMode?(attack?'낯선 Origin · CSRF 토큰 없음':'신뢰한 Origin · 유효한 CSRF 토큰'):'로그인 쿠키만 검사'];data=blocked?'요청 거부 · 잔액 500':`가상 송금 100 · 잔액 400`;}
if(id===23){trace=[`target = ${input}`,`가상 네트워크 = ${attack?'내부':'외부'}`,protectedMode?'호스트·주소 허용 목록 검사':'목적지 검사 없음'];data=blocked?'내부 목적지 거부':attack?'가상 내부 서비스: maintenance=true':'가상 공개 이미지: banner.png';}
if(id===24){blocked=attack&&protectedMode;status=!attack?401:blocked?401:200;trace=['계정 analyst-a',`비밀번호 비교 → ${attack?'일치':'불일치'}`,protectedMode?'독립적인 추가 인증 필요':'비밀번호만 확인'];data=attack?(protectedMode?'추가 인증 없음 · 로그인 거부':'가상 로그인 성공'):'비밀번호 불일치';}
if(id===25){const parts=[];for(const p of ('/reports/'+input).split('/')){if(p==='..')parts.pop();else if(p&&p!=='.')parts.push(p);}const path='/'+parts.join('/');trace=[`input = ${input}`,`resolved = ${path}`,protectedMode?'공개 디렉터리 경계 검사':'경로 연결만 수행'];data=blocked?'공개 폴더 밖 접근 거부':attack?'가상 사고 파일: backup=offline':'가상 공개 파일: report ready';}
if(id===26){trace=[`package = ${input}`,`checksum = ${attack?'demo-untrusted':'demo-approved'}`,protectedMode?'고정된 이름·체크섬 검사':'레지스트리 이름만 사용'];data=blocked?'패키지 검증 실패 · 설치 중단':attack?'가상 설치 훅 실행: 설정 읽기':'가상 공식 패키지 설치';}
return {status,trace,data,code:protectedMode?spec.fixed:spec.code,exposed:attack&&!blocked,blocked,patch,recorded:false,model:true};}
export function validateScenario(id,step,a,seed){if(step===2)return a===1;if(step!==0&&step!==1)return false;const spec=scenarioSpec(id,seed);if(!spec||a?.input!==spec.exploit)return false;const result=scenarioLab(id,seed,a.input,step===0?'none':a.patch);return !!result&&(step===0?result.exposed:result.blocked&&a.patch===spec.patch);}
export function randomStep(value){let n=(Math.imul(value,1664525)+1013904223)>>>0;return {state:n,value:n/4294967296};}
export function reverseSpec(seed){const key=(seed>>>0)%7+3,secret=20+((seed>>>3)%40);return {key,target:secret^key};}
export function reverseTrace(seed,input){if(!Number.isInteger(input)||input<0||input>255)return null;const {key,target}=reverseSpec(seed),mixed=input^key;return {key,target,input,mixed,opened:mixed===target};}
export function sqlLab(input,mode){if(typeof input!=='string'||input.length>80||!['concat','parameter'].includes(mode))return null;const injection=input==="' OR '1'='1"||input==="Byte' OR '1'='1";if(!injection&&!/^[a-zA-Z ]{0,20}$/.test(input))return null;const prefix="WITH demo(name) AS (VALUES ('Byte'), ('Nori'), ('Coco')) SELECT name FROM demo WHERE name = ";return {query:prefix+(mode==='parameter'?'?':"'"+input+"'"),params:mode==='parameter'?[input]:[],rows:mode==='concat'&&injection?['Byte','Nori','Coco']:['Byte','Nori','Coco'].filter(name=>name===input),injection,mode};}
export function packetSpecs(seed){let state=seed>>>0;const next=()=>{let r=randomStep(state);state=r.state;return r.value};return Array.from({length:46},(_,id)=>{const lane=Math.floor(next()*4),bad=next()<.65,label=bad?(next()<.5?'DDoS':'PORT'):(next()<.5?'HTTP':'HTTPS'),speed=48+next()*16;return {id,lane,bad,label,speed,spawn:(id+1)*850,y:45+lane*67};});}
export function packetMetrics(seed,answer,elapsed=Infinity){if(!answer||!Array.isArray(answer.events)||answer.events.length>100||!Number.isInteger(answer.end)||answer.end<1||answer.end>40000||answer.end>elapsed+800)return null;const specs=packetSpecs(seed),blocked=new Set();let count=0,errors=0,last=0;for(const e of answer.events){if(!e||!Number.isInteger(e.id)||!Number.isInteger(e.time)||e.time<last||e.time>answer.end)return null;last=e.time;const p=specs[e.id];if(!p||blocked.has(e.id)||e.time<p.spawn||36+p.speed*(e.time-p.spawn)/1000>586)return null;blocked.add(e.id);if(p.bad)count++;else errors++;}for(const p of specs)if(p.bad&&!blocked.has(p.id)&&p.spawn+(550/p.speed*1000)<=answer.end)errors++;return {count,errors};}
export function validatePacketReplay(seed,answer,elapsed=Infinity){const result=packetMetrics(seed,answer,elapsed);return !!result&&result.count>=8&&result.errors<5;}
export function snakeFood(s){for(let i=0;i<300;i++){let r=randomStep(s.rng);s.rng=r.state;const x=Math.floor(r.value*16);r=randomStep(s.rng);s.rng=r.state;const y=Math.floor(r.value*16);if(!s.body.some(p=>p.x===x&&p.y===y)&&!s.mines.some(p=>p.x===x&&p.y===y))return{x,y};}return{x:0,y:0};}
export function snakeInitial(seed){let s={body:[{x:8,y:8},{x:7,y:8},{x:6,y:8}],direction:1,rng:seed>>>0,mines:[{x:3,y:3},{x:12,y:3},{x:3,y:12}],score:0,ended:false,ticks:0};s.food=snakeFood(s);return s;}
export function snakeStep(s,requested){if(s.ended)return s;const moves=[[0,-1],[1,0],[0,1],[-1,0]];let dir=Number.isInteger(requested)&&requested>=0&&requested<4?requested:s.direction;if((dir+2)%4===s.direction)dir=s.direction;s.direction=dir;let [dx,dy]=moves[dir],head={x:(s.body[0].x+dx+16)%16,y:(s.body[0].y+dy+16)%16};let eats=head.x===s.food.x&&head.y===s.food.y;let body=eats?s.body:s.body.slice(0,-1);s.ticks++;if(body.some(p=>p.x===head.x&&p.y===head.y)||s.mines.some(p=>p.x===head.x&&p.y===head.y)){s.ended=true;return s;}s.body.unshift(head);if(!eats)s.body.pop();else{s.score++;s.food=snakeFood(s);}return s;}
export function validateSnakeReplay(seed,answer,elapsed=Infinity){if(!answer||!Array.isArray(answer.moves)||answer.moves.length>512||answer.moves.length<1||answer.moves.length*180>elapsed+800)return false;let s=snakeInitial(seed);for(const dir of answer.moves){if(!Number.isInteger(dir)||dir<0||dir>3||s.ended||s.score>=4)return false;snakeStep(s,dir);}return !s.ended&&s.score>=4;}
export function snakeAhead(s,requested=s.direction){const dir=(requested+2)%4===s.direction?s.direction:requested;const [dx,dy]=[[0,-1],[1,0],[0,1],[-1,0]][dir];return {x:(s.body[0].x+dx+16)%16,y:(s.body[0].y+dy+16)%16};}
export function snakeLabStep(s,dir,hook){if(hook==='ahead')s.food=snakeAhead(s,dir);return snakeStep(s,dir);}
export function validateSnakeLab(seed,a,elapsed=Infinity){if(a?.hook!=='ahead'||!Array.isArray(a.moves)||a.moves.length<4||a.moves.length>128||a.moves.length*180>elapsed+100)return false;const s=snakeInitial(seed);for(const dir of a.moves){if(!Number.isInteger(dir)||dir<0||dir>3||s.ended||s.score>=4)return false;snakeLabStep(s,dir,'ahead');}return !s.ended&&s.score===4&&a.score===s.score&&a.length===s.body.length;}
export function labProbe(id,seed,report,elapsed=Infinity,patch){if(!report||typeof report!=='object'||Array.isArray(report))return null;let value,valid,reason;if(id===12){value=report.score;valid=report.mode!=='ahead'&&validateSnakeReplay(seed,report,elapsed)&&value===4;reason='서버가 원래 먹이 규칙으로 이동 기록을 재실행해. 보낸 점수나 먹이 함수는 믿지 않아.';}else if(id===3){value=report.blocked;const m=packetMetrics(seed,report,elapsed);valid=!!m&&m.count===value&&validatePacketReplay(seed,report,elapsed);reason='서버가 패킷 시드·클릭 시간·중복을 검사해. blocked 숫자만 바꿔도 실제 방어가 되지는 않아.';}else if(id===13){value=report.points;valid=report.points===5&&report.blockVirus===true&&report.tested===true;reason='서버가 이 실습의 허용 규칙(5점·방어 켜짐)을 검사해. 클라이언트의 999점은 거부해.';}else if(id===19){value=report.arrived?999:0;valid=validateRobot(report.moves);reason='서버가 이동 명령을 다시 실행해. arrived: true를 보내도 바이러스를 지나거나 목표에 못 가면 거부해.';}else return null;if(!Number.isInteger(value)||value<0||value>1000000)return null;return {vulnerable:{accepted:value>=4,claimed:value},secure:{accepted:valid,reason},...(id===12&&['client-lock','server-replay'].includes(patch)?{patched:{accepted:patch==='server-replay'?valid:value>=4,patch}}:{}),recorded:false};}
export function validateRobot(answer){if(!Array.isArray(answer)||answer.length>12||answer.length<4)return false;let x=0,y=0;const moves={U:[0,-1],R:[1,0],D:[0,1],L:[-1,0]};for(const m of answer){if(!moves[m])return false;x+=moves[m][0];y+=moves[m][1];if(x<0||x>3||y<0||y>3||x===1&&y===1)return false;}return x===2&&y===2;}
export function validateAnswer(id,step,a,seed,elapsed){if(id===0&&step===0){if(typeof a!=='string'||a.length>200)return false;return a.length>=14&&/[a-zA-Z가-힣]/.test(a)&&/\d/.test(a)&&/[^a-zA-Z0-9가-힣]/.test(a)&&!/(password|qwerty|123456|hacklingo)/i.test(a)&&!(/^(.)\1+$/u.test(a));}
if(id>=21&&id<=26)return validateScenario(id,step,a,seed);if(id===20)return step===0?reverseTrace(seed,a?.input)?.opened===true:step===1&&a===1;if(id===1)return a===['sender','urgent','link'][step];if(id===2)return a?.line===1&&a?.option===(step===0?0:1);if(id===3)return validatePacketReplay(seed,a,elapsed);if(id===5&&step===0)return a==='scanned';if(id===8&&step===0)return Array.isArray(a)&&a.length===2&&a.includes('address')&&a.includes('school');if(id===10&&step===0)return a?.contacts===false&&a?.mic===false&&a?.location===false;if(id===12){if(step===0)return validateSnakeLab(seed,a,elapsed);if(step===1){const probe=labProbe(12,seed,a?.report,elapsed);return a?.patch==='server-replay'&&a?.tested===true&&probe?.vulnerable.accepted===true&&probe?.secure.accepted===false;}return step===2&&a===1;}if(id===13&&step===0)return a?.points===5&&a?.blockVirus===true&&a?.tested===true;if(id===14&&step===0)return typeof a==='string'&&a.trim().toUpperCase()==='BYTE';if(id===19)return validateRobot(a);const answers={0:[null,0],4:[1,1],5:[null,1],6:[1,1],7:[1,1],8:[null,1],9:[0,1],10:[null,1],11:[2,0],13:[null,1],14:[null,1],15:[1,1],16:[2,0],17:[1,1],18:[0,1]};return a===answers[id]?.[step]&&a!==undefined;}
