import {XP,STEPS,validateAnswer,packetMetrics,labProbe,sqlLab,scenarioLab} from './rules.mjs';
const AVATARS=['🧑‍🚀','🐿️','🦊','🐱','🐼','🐰'];
const utcDay=()=>new Date().toISOString().slice(0,10);
const randomHex=(n=24)=>Array.from(crypto.getRandomValues(new Uint8Array(n)),b=>b.toString(16).padStart(2,'0')).join('');
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
function error(message,status=400){throw Object.assign(new Error(message),{status});}
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});}
const query=(db,sql,...args)=>db.prepare(sql).bind(...args);
async function rate(db,key,max){const now=Date.now(),window=Math.floor(now/60000);const r=await query(db,'INSERT INTO rate_limits (key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count = count + 1 RETURNING count',key+':'+window,now+120000).first();if(r.count>max)error('잠깐 쉬었다가 1분 뒤에 다시 해줘.',429);if(Math.random()<.01)await query(db,'DELETE FROM rate_limits WHERE expires_at < ?',now).run();}
async function playerFor(req,db){const cookie=req.headers.get('Cookie')||'',token=cookie.match(/(?:^|;\s*)hl_session=([a-f0-9]{48})(?:;|$)/)?.[1];if(!token)return null;return query(db,'SELECT p.* FROM players p JOIN sessions s ON s.player_id=p.id WHERE s.token_hash=? AND s.expires_at>?',await hash(token),Date.now()).first();}
async function newSession(db,playerId,url){const token=randomHex();await query(db,'INSERT INTO sessions (token_hash,player_id,expires_at) VALUES (?,?,?)',await hash(token),playerId,Date.now()+90*86400000).run();return `hl_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=7776000${url.protocol==='https:'?'; Secure':''}`;}
function nickname(value){if(typeof value!=='string')error('닉네임을 적어줘.');const s=value.trim().normalize('NFC');if(s.length<2||s.length>16||!/^[-_ a-zA-Z0-9가-힣]+$/u.test(s))error('닉네임은 2~16자 한글·영문·숫자로 적어줘.');return s;}
async function profile(db,p){const fresh=await query(db,'SELECT nickname,avatar,hearts FROM players WHERE id=?',p.id).first();if(fresh)p={...p,...fresh};const day=utcDay();const [totals,daily,correct,claims,completed,days]=await Promise.all([query(db,'SELECT COALESCE(SUM(xp),0) xp, COALESCE(SUM(gems),0) gems FROM completions WHERE player_id=?',p.id).first(),query(db,'SELECT COUNT(*) lessons,COALESCE(SUM(xp),0) xp FROM completions WHERE player_id=? AND day=?',p.id,day).first(),query(db,'SELECT COUNT(*) correct FROM answers WHERE player_id=? AND day=?',p.id,day).first(),query(db,'SELECT quest_id,gems FROM quest_claims WHERE player_id=?',p.id).all(),query(db,'SELECT DISTINCT mission_id FROM completions WHERE player_id=?',p.id).all(),query(db,'SELECT DISTINCT day FROM completions WHERE player_id=? ORDER BY day DESC LIMIT 366',p.id).all()]);let streak=0,cursor=new Date(day+'T00:00:00Z');if(days.results[0]?.day!==day)cursor.setUTCDate(cursor.getUTCDate()-1);for(const row of days.results){if(row.day!==cursor.toISOString().slice(0,10))break;streak++;cursor.setUTCDate(cursor.getUTCDate()-1);}const todayClaims=await query(db,'SELECT quest_id FROM quest_claims WHERE player_id=? AND day=?',p.id,day).all();return{id:p.id,nickname:p.nickname,avatar:AVATARS[p.avatar]||AVATARS[0],avatarIndex:p.avatar,xp:totals.xp,gems:totals.gems+claims.results.reduce((s,r)=>s+r.gems,0),hearts:p.hearts,streak,completed:completed.results.map(r=>r.mission_id),daily:{date:day,lessons:daily.lessons,xp:daily.xp,correct:correct.correct,claims:todayClaims.results.map(r=>r.quest_id)}};}
async function board(db,p,scope){const week=new Date(Date.now()-6*86400000).toISOString().slice(0,10);const rows=await query(db,`SELECT p.id,p.nickname,p.avatar,SUM(c.xp) xp FROM players p JOIN completions c ON c.player_id=p.id ${scope==='weekly'?'WHERE c.day>=?':''} GROUP BY p.id ORDER BY xp DESC,p.created_at ASC LIMIT 100`,...(scope==='weekly'?[week]:[])).all();return {scope,rows:rows.results.map((r,i)=>({rank:i+1,name:r.nickname,icon:AVATARS[r.avatar]||AVATARS[0],xp:r.xp,mine:r.id===p?.id})),updatedAt:Date.now()};}
async function getRoom(db,code,p){const room=await query(db,'SELECT * FROM rooms WHERE code=? AND expires_at>?',code,Date.now()).first();if(!room)error('방을 찾을 수 없어. 코드나 유효 시간을 확인해줘.',404);const member=await query(db,'SELECT * FROM room_members WHERE room_code=? AND player_id=?',code,p.id).first();if(!member)error('먼저 방 코드로 참가해줘.',403);await query(db,'UPDATE room_members SET seen_at=? WHERE room_code=? AND player_id=?',Date.now(),code,p.id).run();const members=await query(db,'SELECT p.id,p.nickname,p.avatar,m.seen_at,m.score,m.finished_at,(SELECT MAX(a.step) FROM attempts a WHERE a.player_id=p.id AND a.room_code=m.room_code) progress FROM room_members m JOIN players p ON p.id=m.player_id WHERE m.room_code=? ORDER BY m.score DESC,COALESCE(m.finished_at,9223372036854775807) ASC,m.joined_at ASC',code).all();return {code,missionId:room.mission_id,status:room.status,startsAt:room.starts_at,expiresAt:room.expires_at,host:room.owner_id===p.id,members:members.results.map((m,i)=>({name:m.nickname,icon:AVATARS[m.avatar],mine:m.id===p.id,host:m.id===room.owner_id,online:m.seen_at>Date.now()-20000,score:m.score,finished:!!m.finished_at,progress:m.progress||0,rank:i+1}))};}
export async function handleApi(req,env){const db=env.DB;if(!db)return json({error:'공유 서버가 아직 연결되지 않았어. 혼자 연습은 가능해.'},503);const url=new URL(req.url),path=url.pathname;try{let body={};if(req.method==='POST'){if(req.headers.get('Origin')!==url.origin)error('이 사이트에서 다시 시도해줘.',403);if(!req.headers.get('Content-Type')?.startsWith('application/json'))error('JSON 요청이 필요해.',415);const raw=await req.text();if(raw.length>20000)error('요청이 너무 커.',413);try{body=JSON.parse(raw)}catch{error('요청을 읽을 수 없어.')}if(!body||Array.isArray(body)||typeof body!=='object')error('요청 형식이 올바르지 않아.');}
const p=await playerFor(req,db);if(req.method==='GET'&&path==='/api/me')return json({player:p?await profile(db,p):null});if(req.method==='GET'&&path==='/api/leaderboard')return json(await board(db,p,url.searchParams.get('scope')==='weekly'?'weekly':'all'));
if(req.method==='POST'&&(path==='/api/profile'||path==='/api/restore')){const ip=req.headers.get('CF-Connecting-IP')||'local';await rate(db,'identity:'+await hash(ip),12);if(path==='/api/restore'){if(typeof body.code!=='string'||!/^HL-[a-f0-9]{24}$/i.test(body.code.trim()))error('복구 코드를 확인해줘.');const found=await query(db,'SELECT * FROM players WHERE recovery_hash=?',await hash(body.code.trim().toUpperCase())).first();if(!found)error('복구 코드를 찾을 수 없어.',401);return json({player:await profile(db,found)},200,{'Set-Cookie':await newSession(db,found.id,url)});}const name=nickname(body.nickname);const avatar=Number.isInteger(body.avatar)&&body.avatar>=0&&body.avatar<AVATARS.length?body.avatar:0;if(p){await query(db,'UPDATE players SET nickname=?,avatar=? WHERE id=?',name,avatar,p.id).run();return json({player:await profile(db,{...p,nickname:name,avatar})});}const id=crypto.randomUUID(),recoveryCode='HL-'+randomHex(12).toUpperCase(),created=Date.now();await query(db,'INSERT INTO players (id,nickname,avatar,recovery_hash,created_at) VALUES (?,?,?,?,?)',id,name,avatar,await hash(recoveryCode),created).run();const createdPlayer={id,nickname:name,avatar,hearts:5};return json({player:await profile(db,createdPlayer),recoveryCode},201,{'Set-Cookie':await newSession(db,id,url)});}
if(!p)error('닉네임으로 참가하면 함께 할 수 있어.',401);if(req.method==='POST')await rate(db,'player:'+p.id,120);
if(req.method==='POST'&&path==='/api/labs/scenario'){const attempt=await query(db,"SELECT * FROM attempts WHERE id=? AND player_id=? AND mission_id BETWEEN 21 AND 26 AND status='active' AND expires_at>?",body.attemptId,p.id,Date.now()).first();if(!attempt)error('현재 보안 실습을 먼저 시작해줘.',404);const result=scenarioLab(attempt.mission_id,attempt.seed,body.input,body.patch);if(!result)error('제공된 가상 입력과 패치를 사용해줘.');return json({...result,source:'server-model'});}
if(req.method==='POST'&&path==='/api/labs/sql'){const attempt=await query(db,"SELECT * FROM attempts WHERE id=? AND player_id=? AND mission_id=2 AND status='active' AND expires_at>?",body.attemptId,p.id,Date.now()).first();if(!attempt)error('코드 수리 실습을 먼저 시작해줘.',404);const lab=sqlLab(body.input,body.mode);if(!lab)error('Byte, Nori, Coco 또는 제공된 OR 실습 입력만 사용해줘.');const result=await query(db,lab.query,...lab.params).all();return json({...lab,rows:result.results.map(row=>row.name),source:'server-sql',recorded:false});}
if(req.method==='POST'&&path==='/api/labs/probe'){const attempt=await query(db,"SELECT * FROM attempts WHERE id=? AND player_id=? AND status='active' AND expires_at>?",body.attemptId,p.id,Date.now()).first();if(!attempt)error('현재 실습을 먼저 시작해줘.',404);const result=labProbe(attempt.mission_id,attempt.seed,body.report,Date.now()-attempt.last_step_at,body.patch);if(!result)error('이 실습에서 지원하는 요청 형식을 확인해줘.');return json({...result,source:'server',missionId:attempt.mission_id});}
if(req.method==='POST'&&path==='/api/logout'){const token=(req.headers.get('Cookie')||'').match(/(?:^|;\s*)hl_session=([a-f0-9]{48})(?:;|$)/)?.[1];if(token)await query(db,'DELETE FROM sessions WHERE token_hash=?',await hash(token)).run();return json({ok:true},200,{'Set-Cookie':'hl_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0'});}
if(req.method==='POST'&&path==='/api/recover'){await query(db,'UPDATE players SET hearts=5 WHERE id=?',p.id).run();return json({player:await profile(db,{...p,hearts:5})});}
if(req.method==='POST'&&path==='/api/quests/claim'){const id=body.questId,q=[{key:'lessons',goal:1,gems:10},{key:'xp',goal:50,gems:15},{key:'correct',goal:5,gems:10}][id];if(!Number.isInteger(id)||!q)error('퀘스트를 찾을 수 없어.');const data=await profile(db,p);if(data.daily[q.key]<q.goal)error('아직 도전을 완료하지 않았어.');await query(db,'INSERT INTO quest_claims (player_id,day,quest_id,gems) VALUES (?,?,?,?) ON CONFLICT(player_id,day,quest_id) DO NOTHING',p.id,utcDay(),id,q.gems).run();return json({player:await profile(db,p)});}
if(req.method==='POST'&&path==='/api/rooms'){const id=body.missionId;if(!Number.isInteger(id)||!XP[id])error('미션을 선택해줘.');await rate(db,'create-room:'+p.id,5);let code=Array.from(crypto.getRandomValues(new Uint8Array(6)),b=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[b%32]).join('');let now=Date.now();await db.batch([query(db,'INSERT INTO rooms (code,owner_id,mission_id,expires_at,created_at) VALUES (?,?,?,?,?)',code,p.id,id,now+3600000,now),query(db,'INSERT INTO room_members (room_code,player_id,joined_at,seen_at) VALUES (?,?,?,?)',code,p.id,now,now)]);return json({room:await getRoom(db,code,p)},201);}
if(req.method==='POST'&&path==='/api/rooms/join'){await rate(db,'join-room:'+p.id,12);const code=typeof body.code==='string'?body.code.trim().toUpperCase():'';if(!/^[A-Z2-9]{6}$/.test(code))error('방 코드는 영문·숫자 6자리야.');const room=await query(db,'SELECT * FROM rooms WHERE code=? AND expires_at>?',code,Date.now()).first();if(!room)error('방을 찾을 수 없어.',404);const member=await query(db,'SELECT player_id FROM room_members WHERE room_code=? AND player_id=?',code,p.id).first();if(!member){if(room.status!=='lobby')error('이미 출동한 방이야. 새 방에서 함께 시작해줘.',409);const now=Date.now();const inserted=await query(db,'INSERT INTO room_members (room_code,player_id,joined_at,seen_at) SELECT ?,?,?,? WHERE (SELECT COUNT(*) FROM room_members WHERE room_code=?) < 20',code,p.id,now,now,code).run();if(!inserted.meta.changes)error('방이 꽉 찼어. 최대 20명이 함께 할 수 있어.',409);}return json({room:await getRoom(db,code,p)});}
const roomMatch=path.match(/^\/api\/rooms\/([A-Z2-9]{6})(?:\/(start|leave))?$/);if(roomMatch){const code=roomMatch[1];if(req.method==='GET'&&!roomMatch[2])return json({room:await getRoom(db,code,p)});if(req.method==='POST'&&roomMatch[2]==='start'){const room=await query(db,'SELECT * FROM rooms WHERE code=? AND owner_id=? AND expires_at>?',code,p.id,Date.now()).first();if(!room)error('방장만 출동을 시작할 수 있어.',403);await query(db,"UPDATE rooms SET status='active',starts_at=? WHERE code=? AND status='lobby'",Date.now()+4000,code).run();return json({room:await getRoom(db,code,p)});}if(req.method==='POST'&&roomMatch[2]==='leave'){const r=await query(db,'SELECT owner_id FROM rooms WHERE code=?',code).first();if(r?.owner_id===p.id)await query(db,'UPDATE rooms SET expires_at=? WHERE code=?',Date.now(),code).run();else await query(db,'DELETE FROM room_members WHERE room_code=? AND player_id=?',code,p.id).run();return json({ok:true});}}
if(req.method==='POST'&&path==='/api/attempts/start'){const id=body.missionId;if(!Number.isInteger(id)||!XP[id])error('미션을 찾을 수 없어.');await rate(db,'attempt:'+p.id,30);let roomCode=null;if(body.roomCode){const room=await getRoom(db,body.roomCode,p);if(room.status!=='active'||Date.now()<room.startsAt||room.missionId!==id)error('같은 방의 출동 시간과 미션을 확인해줘.',409);if(room.members.find(m=>m.mine)?.finished)error('이 방의 미션은 이미 완료했어. 새 방에서 다시 도전해줘.',409);roomCode=room.code;}const now=Date.now(),attemptId=crypto.randomUUID(),seed=crypto.getRandomValues(new Uint32Array(1))[0];await query(db,'INSERT INTO attempts (id,player_id,mission_id,room_code,seed,created_at,last_step_at,expires_at) VALUES (?,?,?,?,?,?,?,?)',attemptId,p.id,id,roomCode,seed,now,now,now+30*60000).run();return json({attempt:{id:attemptId,seed,step:0}},201);}
const answerMatch=path.match(/^\/api\/attempts\/([a-f0-9-]{36})\/answer$/);if(req.method==='POST'&&answerMatch){const attempt=await query(db,'SELECT * FROM attempts WHERE id=? AND player_id=? AND expires_at>?',answerMatch[1],p.id,Date.now()).first();if(!attempt)error('연습 시간이 끝났어. 미션을 다시 열어줘.',404);if(attempt.status==='complete')return json({correct:true,complete:true,alreadyComplete:true,awarded:false,player:await profile(db,p)});if(!Number.isInteger(body.step)||body.step!==attempt.step)error('현재 단서부터 해결해줘.',409);if(p.hearts===0)error('하트를 무료로 회복해줘.',409);const elapsed=Date.now()-attempt.last_step_at,metrics=attempt.mission_id===3?packetMetrics(attempt.seed,body.answer,elapsed):null;const correct=validateAnswer(attempt.mission_id,attempt.step,body.answer,attempt.seed,elapsed)&&(attempt.mission_id!==3||metrics.errors<p.hearts);const penalty=attempt.mission_id===3&&metrics?Math.max(correct?0:1,metrics.errors):correct?0:1;if(penalty)await query(db,'UPDATE players SET hearts=MAX(0,hearts-?) WHERE id=?',penalty,p.id).run();if(!correct){return json({correct:false,player:await profile(db,{...p,hearts:Math.max(0,p.hearts-1)})});}const now=Date.now(),day=utcDay(),complete=attempt.step+1>=STEPS[attempt.mission_id];const commands=[query(db,"UPDATE attempts SET step=step+1,status=?,last_step_at=? WHERE id=? AND step=? AND status='active'",complete?'complete':'active',now,attempt.id,body.step),query(db,'INSERT INTO answers (player_id,day,mission_id,step) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM attempts WHERE id=? AND step=?) ON CONFLICT(player_id,day,mission_id,step) DO NOTHING',p.id,day,attempt.mission_id,attempt.step,attempt.id,body.step+1)];if(complete){commands.push(query(db,'INSERT INTO completions (player_id,mission_id,day,xp,gems,created_at) SELECT ?,?,?,?,5,? WHERE EXISTS(SELECT 1 FROM attempts WHERE id=? AND status=\'complete\') ON CONFLICT(player_id,mission_id,day) DO NOTHING',p.id,attempt.mission_id,day,XP[attempt.mission_id],now,attempt.id));if(attempt.room_code)commands.push(query(db,'UPDATE room_members SET score=?,finished_at=? WHERE room_code=? AND player_id=? AND finished_at IS NULL',XP[attempt.mission_id],now,attempt.room_code,p.id));}const results=await db.batch(commands);return json({correct:true,complete,awarded:complete&&results[2].meta.changes>0,player:await profile(db,p)});}
return json({error:'이 기능을 찾을 수 없어.'},404);
}catch(e){if(!e.status)console.error('API error:',e.message);return json({error:e.status?e.message:'서버에 잠시 문제가 있어. 저장되지 않은 결과는 다시 시도할 수 있어.'},e.status||503);}}
export function createWorker(html){return {async fetch(req,env){const url=new URL(req.url);if(url.pathname.startsWith('/api/'))return handleApi(req,env);if(req.method!=='GET'&&req.method!=='HEAD')return new Response('Method not allowed',{status:405});if(!['/','/index.html'].includes(url.pathname))return new Response('Not found',{status:404});return new Response(req.method==='HEAD'?null:html,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'",'Permissions-Policy':'camera=(), microphone=(), geolocation=()'}});}};}
